"""empty message

Revision ID: 104602657584
Revises: 8f96da0319d0
Create Date: 2023-02-18 11:34:24.899435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104602657584'
down_revision = '8f96da0319d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('image_url', sa.String(length=120), nullable=False),
    sa.Column('music_url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist')
    # ### end Alembic commands ###
