"""empty message

Revision ID: 14f8afc2c950
Revises: d72b53c1f55d
Create Date: 2023-02-02 18:27:25.170349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f8afc2c950'
down_revision = 'd72b53c1f55d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('ticket_quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'ticket_quantity')
    op.drop_column('tickets', 'user_id')
    # ### end Alembic commands ###
