"""empty message

Revision ID: 165d34be6f3a
Revises: 3cb3ba783c6e
Create Date: 2023-02-04 09:08:06.768085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165d34be6f3a'
down_revision = '3cb3ba783c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image_url', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'news', ['image_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('news', 'image_url')
    # ### end Alembic commands ###
