"""empty message

Revision ID: 336caaa3f4eb
Revises: e527c805c61c
Create Date: 2023-02-04 11:48:32.429350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336caaa3f4eb'
down_revision = 'e527c805c61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('poster_news', sa.Integer(), nullable=True))
    op.alter_column('news', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_foreign_key(None, 'news', 'user', ['poster_news'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.alter_column('news', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('news', 'poster_news')
    # ### end Alembic commands ###
