"""empty message

Revision ID: 4c7a00f11e22
Revises: 02648731222f
Create Date: 2023-02-02 18:57:30.178261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7a00f11e22'
down_revision = '02648731222f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_user_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tickets_user_id_fkey', 'tickets', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
