"""empty message

Revision ID: 8f96da0319d0
Revises: 4d19fd91b6cb
Create Date: 2023-02-18 11:19:56.159058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f96da0319d0'
down_revision = '4d19fd91b6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('image_url', sa.String(length=120), nullable=False),
    sa.Column('music_url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('poster_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cloud_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['user.id'], name='images_poster_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.drop_table('artist')
    # ### end Alembic commands ###
