"""empty message

Revision ID: a23a688619f4
Revises: fe4b45a7ecee
Create Date: 2023-02-14 11:18:47.697422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23a688619f4'
down_revision = 'fe4b45a7ecee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_constraint('artist_image_id_fkey', type_='foreignkey')
        batch_op.drop_column('image_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint('images_poster_id_fkey', type_='foreignkey')
        batch_op.drop_column('poster_id')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('news_image_id_fkey', type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('news_image_id_fkey', 'images', ['image_id'], ['id'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('images_poster_id_fkey', 'user', ['poster_id'], ['id'])

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('artist_image_id_fkey', 'images', ['image_id'], ['id'])

    # ### end Alembic commands ###
