"""empty message

Revision ID: dac8e9646030
Revises: 14f8afc2c950
Create Date: 2023-02-02 18:54:27.358427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac8e9646030'
down_revision = '14f8afc2c950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_user_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tickets_user_id_fkey', 'tickets', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
