"""empty message

Revision ID: fe4b45a7ecee
Revises: c2a6118c6cae
Create Date: 2023-02-14 11:10:03.023293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4b45a7ecee'
down_revision = 'c2a6118c6cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('music_url', sa.String(length=120), nullable=False))
        batch_op.create_foreign_key(None, 'images', ['image_id'], ['id'])
        batch_op.drop_column('musicUrl')
        batch_op.drop_column('imageUrl')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('news_image_url_key', type_='unique')
        batch_op.create_foreign_key(None, 'images', ['image_id'], ['id'])
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('news_image_url_key', ['image_url'])
        batch_op.drop_column('image_id')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('musicUrl', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('music_url')
        batch_op.drop_column('image_id')

    op.drop_table('images')
    # ### end Alembic commands ###
